### PR TITLE
Fixes issue 8

### PR DESCRIPTION
**Pull request by mchav**
Corrected spelling mistake and function definition.

### CODE REVIEW

**Comment by nphollon** [comment]
This is a great catch. Apparently you are the first person to try calling this function?!

**Comment by mgold** [comment]
This is technically a major version bump because the function signature changed, but it's also clearly a bug fix. @johnpmayer does this look good to you?

**Comment by nphollon** [comment]
(I was surprised to learn that the elm compiler does zero validation on calls to Native. I can see why Evan wants to keep the native whitelist as short as possible!)

**Comment by johnpmayer** [comment]
Yeah this seems fine.

**Pull request merged**
